// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieeobcmbjijtsuavfzfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllZW9iY21iamlqdHN1YXZmemZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjA5MzksImV4cCI6MjA2NjQzNjkzOX0.WHni306OpYTibaHQSFWybo-U4GhIfzhDDrTkJmd1l6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);